<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Service\**" />
    <EmbeddedResource Remove="Service\**" />
    <None Remove="Service\**" />
    <Page Remove="Service\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Util\" />
  </ItemGroup>
  
  <ItemGroup>
    <None Remove="Resource\*.png" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <Resource Include="Resource\*.png" />
    <None Include="target_mysql.json" CopyToOutputDirectory="PreserveNewest" Condition="Exists('target_mysql.json')" />
  </ItemGroup>

</Project>
